services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ERL_FLAGS: "-sname example_app -setcookie mycookie"
    hostname: example_app_host
    ports:
      - "127.0.0.1:1234:1234"

  spectator:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      ERL_FLAGS: "-sname spectator_app -setcookie mycookie"
    ports:
      - "127.0.0.1:3000:3000"
