name = "spectator"
version = "2.1.0"
description = "BEAM observer tool"
licences = ["MIT"]
repository = { type = "github", user = "JonasGruenwald", repo = "spectator", path = "spectator" }

[documentation]
pages = [
  { title = "Changelog", path = "changelog.html", source = "../CHANGELOG.md" },
  { title = "About Spectator", path = "overview.html", source = "../README.md" },
]

[dependencies]
simplifile = ">= 2.2.0 and < 3.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
lustre = ">= 5.0.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
carpenter = { git = "https://github.com/ghivert/carpenter.git", ref = "main" }
embeds = ">= 1.1.2 and < 2.0.0"
